### PR TITLE
Update to Rails 4.2

### PR DESCRIPTION
**Pull request by marten**
I have no real way to check if this upgrade worked. @eatyourgreens any thoughts?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I think Rob used the master branch for the Milky Way Project. I'll check this out and have a look.

**Comment by marten** [comment]
Does that mean we need to do this umpteen times or can we rebase those other branches on top of the new master like a sane release strategy might do?

**Comment by eatyourgreens** [comment]
Rebase (fingers crossed). Twice, not umpteen times, for the Orchids and Science Gossip projects.

**Comment by eatyourgreens** [comment]
Looking good when I run it locally :+1:
image

**Pull request merged**
